let level1;

function initLevel() {
  level1 = new Level(
    [
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Smallchicken(),
      new Smallchicken(),
      new Smallchicken(),
      new Endboss(),
    ],
    [
      new Cloud(250, 0),
      new Cloud(650, 1),
      new Cloud(1050, 0),
      new Cloud(1450, 1),
      new Cloud(1850, 0),
      new Cloud(2250, 0),
      new Cloud(2650, 0),
    ],
    [
      new BackgroundObject("img/5_background/layers/air.png", -720),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", -720),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png",-720,),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", -720),
      new BackgroundObject("img/5_background/layers/air.png", 0),
      new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 0),
      new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 0),
      new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 0),
      new BackgroundObject("img/5_background/layers/air.png", 720),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 720),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 720),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 720),
      new BackgroundObject("img/5_background/layers/air.png", 1440),
      new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 1440),
      new BackgroundObject(
        "img/5_background/layers/2_second_layer/1.png",
        1440,
      ),
      new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 1440),
      new BackgroundObject("img/5_background/layers/air.png", 2160),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 2160),
      new BackgroundObject(
        "img/5_background/layers/2_second_layer/2.png",
        2160,
      ),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 2160),
    ],
    [
      new Coin(400, 300),
      new Coin(500, 200),
      new Coin(550, 200),
      new Coin(650, 300),
      new Coin(1000, 100),
      new Coin(1200, 300),
      new Coin(1400, 300),
    ],
    [
      new Bottle(300, 350),
      new Bottle(750, 350),
      new Bottle(800, 350),
      new Bottle(900, 350),
      new Bottle(1100, 350),
      new Bottle(1200, 350),
      new Bottle(1400, 350),
      new Bottle(1500, 350),
      new Bottle(1600, 350),
    ],
  );
}
