const level1 = new Level(
  [new Chicken(), new Chicken(), new Chicken(), new Endboss()],
  [new Cloud()],
  [
    new BackgroundObject("img/5_background/layers/air.png", -720),
    new BackgroundObject("img/5_background/layers/3_third_layer/2.png", -720),
    new BackgroundObject("img/5_background/layers/2_second_layer/2.png", -720),
    new BackgroundObject("img/5_background/layers/1_first_layer/2.png", -720),
    new BackgroundObject("img/5_background/layers/air.png", 0),
    new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 0),
    new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 0),
    new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 0),
    new BackgroundObject("img/5_background/layers/air.png", 720),
    new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 720),
    new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 720),
    new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 720),
    new BackgroundObject("img/5_background/layers/air.png", 1440),
    new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 1440),
    new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 1440),
    new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 1440),
    new BackgroundObject("img/5_background/layers/air.png", 2160),
    new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 2160),
    new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 2160),
    new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 2160),
  ],
  [
    new Coin(400, 300),
    new Coin(500, 200),
    new Coin(550, 200),
    new Coin(650, 300),
    new Coin(1000, 100),
  ],
  [
    new Bottle(300, 350),
    new Bottle(750, 350),
    new Bottle(800, 350),
    new Bottle(900, 350),
    new Bottle(1100, 350)
  ]
);
